# Generated by Django 3.0.2 on 2020-04-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
